### ISSUE TITLE
Todo list; 2015-06-05

### ISSUE THREAD

**Issue by DoomsdayMuffinz** [FOSS-WebChat/soma#8]
- User list/count
- Timestamps (Both 12- and 24-hour)
- ~~Commands~~ Done
- Server messages (e.g. connect/disconnect messages)

**Comment by LandonPowell** [comment]
Is soma kill?

**Comment by DoomsdayMuffinz** [comment]
Yes.

On Mon, Jan 18, 2016 at 9:29 PM, Landon Powell <notifications@github.com>
wrote:

> Is soma kill?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FOSS-WebChat/soma/issues/8#issuecomment-172727489>.
>



-- 
Kenneth Jensen
kennethjensenb@gmail.com

http://cologate.ml/ [Currently out of service]
http://magdorel.ml/ [Currently out of service]

**Comment by DoomsdayMuffinz** [comment]
RIP
